// import localFont from "next/font/local";
import Header from "../components/Header/Header";
import "./globals.css";
import Link from "next/link";

// const geistSans = localFont({
// 	src: "./fonts/GeistVF.woff",
// 	variable: "--font-geist-sans",
// 	weight: "100 900",
// });
// const geistMono = localFont({
// 	src: "./fonts/GeistMonoVF.woff",
// 	variable: "--font-geist-mono",
// 	weight: "100 900",
// });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="fr">
            <body>
                {/* Header */}
                <Header />

                {/* Nav */}
                <nav>
                    <ul className="flex gap-5 justify-center">
                        <li className="nav-item">
                            <Link href="/">Accueil</Link>
                        </li>
                        <li className="nav-item">
                            <Link href="/blog">Blog</Link>
                        </li>
                        <li className="nav-item">
                            <Link href="/about">A propos</Link>
                        </li>
                    </ul>
                </nav>

                {/* Content */}
                {children}
            </body>
        </html>
    );
}
